#ifndef __DELTA_ETHERCAT_DLL_ERR_H__
#define __DELTA_ETHERCAT_DLL_ERR_H__

typedef enum
{
  ERR_ECAT_NO_ERROR = 0,
  ERR_ECAT_HW_NO_INITIALIZE,
  ERR_ECAT_HW_PWM_INITIAL,
  ERR_ECAT_HW_HAS_INITIALIZED,

  ERR_ECAT_EEPROM_READ = 0x10,
  ERR_ECAT_EEPROM_WRITE,
  ERR_ECAT_ENVIRONMENT_RECORD_DISABLE,
  ERR_ECAT_ENVIRONMENT_RECORD_NO_MATCH,
  ERR_ECAT_ENVIRONMENT_RECORD_FILE_OPEN,
  ERR_ECAT_ENVIRONMENT_RECORD_NOT_CREATE,
  ERR_ECAT_XML_FILE_PATH,
  ERR_ECAT_DEVICE_OPEN,
  ERR_ECAT_NO_DEVICE,
  ERR_ECAT_NO_MASTER,
  ERR_ECAT_NO_SLAVE,
  ERR_ECAT_UNKNOWN_SLAVE,
  ERR_ECAT_IST_CREATE,
  ERR_ECAT_MASTER_CREATE,
  ERR_ECAT_MASTER_REQUEST_STATE,
  ERR_ECAT_MASTER_OPERATION_NOT_READY,
  ERR_ECAT_DELTA_NODE_ID_ALIAS_READ,
  ERR_ECAT_MASTER_GET_SERIAL_NO_WRONG,
  ERR_ECAT_MASTER_GET_SERIAL_NO_TIMEOUT,

  ERR_ECAT_PIPELINE_CORE_TIMER_CREATE = 0x80,
  ERR_ECAT_PIPELINE_CREATE,
  ERR_ECAT_COMMAND_ENQUEUE,
  ERR_ECAT_API_BUFFER_ENQUEUE,

  ERR_ECAT_NODE_ID = 0x100,
  ERR_ECAT_SLOT_ID,
  ERR_ECAT_SDO_DOWNLOAD,
  ERR_ECAT_SDO_UPLOAD,
  ERR_ECAT_GET_PROCESS_DATA,

  ERR_ECAT_DIO_CHANNEL_INVALID = 0x200,
  ERR_ECAT_ADDA_CHANNEL_INVALID,
  ERR_ECAT_MOTION_NOT_FINISHED,
  ERR_ECAT_SET_PULSE_MODE,
  ERR_ECAT_SET_SOFTLIMIT,
  ERR_ECAT_SET_POSITION,
  ERR_ECAT_GET_SPEED,
  ERR_ECAT_GET_MCDONE,
  ERR_ECAT_SET_HOME_CONFIG,
  ERR_ECAT_SET_P2P_CONFIG,
  ERR_ECAT_SET_PT_CONFIG,
  ERR_ECAT_SET_PV_CONFIG,
  ERR_ECAT_SET_CSP_CONFIG,
  ERR_ECAT_SET_MULTI_AXES_LINE_CONFIG,
  ERR_ECAT_SET_MULTI_AXES_ARC_CONFIG,

  ERR_ECAT_MD1_SET_GEAR = 0x300,
  ERR_ECAT_MD1_SET_P_CHANGE,
  ERR_ECAT_MD1_SET_V_CHANGE,
  ERR_ECAT_MD1_SET_SOFTLIMIT,
  ERR_ECAT_MD1_SET_SLD,
  ERR_ECAT_MD1_SET_HOME_CONFIG,
  ERR_ECAT_MD1_SET_P2P_CONFIG,
  ERR_ECAT_MD1_SET_V_MOVE_CONFIG,
  ERR_ECAT_MD1_SET_LINE_CONFIG,
  ERR_ECAT_MD1_SET_ARC_CONFIG,

  ERR_ECAT_PATH_NOT_SUPPORT = 0x400,
  ERR_ECAT_PATH_AXIS_NUM,
  ERR_ECAT_PATH_AXIS_NO,
  ERR_ECAT_PATH_PARA,
  ERR_ECAT_PATH_ISR_FUNC_EVENT,
  ERR_ECAT_PATH_AXISNO_UNDER_GROUP,

  ERR_ECAT_PATH_ROBOT_NOT_SUPPORT = 0x480,
  ERR_ECAT_PATH_ROBOT_STOP,
  ERR_ECAT_PATH_ROBOT_AXIS_OVERFLOW,
  ERR_ECAT_PATH_ROBOT_BUFFER_FULL,

  ERR_ESI_INITIAL = 0xF00,
  ERR_ESI_OPEN_DEVICE,
  ERR_ESI_CREATE_CANOPEN_OD_LIST,
  ERR_ESI_NO_DATA_TYPE_INFO,
  ERR_ESI_NO_OBJECT_INFO,
  ERR_ESI_CREATE_SYNC_MANAGER,
  ERR_ESI_CREATE_FMMU_CONTROL,
  ERR_ESI_NO_PDO_CHANNEL,
  ERR_ESI_NO_PDO_MAPPING,
  ERR_ESI_PDO_MAPPING_INSERT,
  ERR_ESI_PDO_MAPPING_DELETE,
  ERR_ESI_CREATE_DISTRIBUTED_CLOCK,

  ERR_ESI_ENI_INFORMATION_INITIAL = 0xFF0,
  ERR_ESI_ENI_FILE_INITIAL,
  ERR_ESI_ENI_FILE_SAVE,

  ERR_ECAT_NO_SLAVE_FOUND = 0x1000,
  ERR_ECAT_INITIAL_TIMEOUT,
  ERR_ECAT_MODE_CHANGE_FAILED,
  ERR_ECAT_SLAVE_ID,
  ERR_ECAT_ALIAS_SLAVE_ID,

  ERR_ECAT_NEED_INITIAL = 0x1100,
  ERR_ECAT_NEED_RESET,
  ERR_ECAT_NEED_CONNECT,
  ERR_ECAT_NEED_DC_OP,
  ERR_ECAT_NEED_RALM,
  ERR_ECAT_NEED_SVON,
  ERR_ECAT_NEED_HOMECONFIG,
  ERR_ECAT_NEED_STOP,
  ERR_ECAT_NEED_STOP_TOUCH_PROBE_HOMING,  // 2018-02-07 from L221
  ERR_ECAT_NEED_STOP_GANTRY,  // 2018-02-07 from L221

  ERR_ECAT_RING_BUFFER_FULL = 0x1200,
  ERR_ECAT_API_PARAMETER,
  ERR_ECAT_SLAVE_TYPE,
  ERR_ECAT_TARGET_REACHED,
  ERR_ECAT_MODE_NOT_SUPPORT,
  ERR_ECAT_MOTION_TYPE,
  ERR_ECAT_PDO_NOT_MAPPING,
  ERR_ECAT_MODULE_REVISION,
  ERR_ECAT_SPEED_CONTINUE_MODE,
  ERR_ECAT_HOME_MODE,
  ERR_ECAT_HOME_OFFSET,
  ERR_ECAT_HOME_FIRST_SPEED,
  ERR_ECAT_HOME_SECOND_SPEED,
  ERR_ECAT_HOME_ACC,
  ERR_ECAT_MRAM_INDEX,
  ERR_ECAT_MRAM_INDEX_OUT_RANGE,
  ERR_ECAT_REACH_SWLIMIT,  // 2018-02-07 from L221
  ERR_ECAT_NEED_ENABLE,  // 2018-02-07 form L221
  ERR_ECAT_DATA_SIZE_OVERFLOW,  // 2018-02-07 from L221
  ERR_ECAT_COOR_ALREADY_USED,  // 2018-02-07 from L221
  ERR_ECAT_COOR_AXIS_ALREADY_USED,  // 2018-02-07 from L221

  ERR_ECAT_PDO_TX_FAILED = 0x1300,
  ERR_ECAT_SDO_TIMEOUT,
  ERR_ECAT_SDO_RETURN,
  ERR_ECAT_PDO_RX_FAILED,
  ERR_ECAT_MAILBOX,
  ERR_ECAT_SDO_BUFFER_FULL,
  ERR_ECAT_ESC_FAILED,  // 2018-02-07 from PAC

  ERR_ECAT_GROUP_NUMBER = 0x1400,
  ERR_ECAT_GROUP_ENABLE,
  ERR_ECAT_GROUP_PAUSE,
  ERR_ECAT_GROUP_SLAVE,
  ERR_ECAT_GROUP_MODE,
  ERR_ECAT_GROUP_ALREADY_USED,
  ERR_ECAT_GROUP_TYPE,
  ERR_ECAT_GROUP_SVON,
  ERR_ECAT_GROUP_ALM,
  ERR_ECAT_GROUP_DATA_BUFFER,
  ERR_ECAT_GROUP_TIMEOUT,

  ERR_ECAT_SERVO_PARA_EMPTY = 0x1500,
  ERR_ECAT_SERVO_PARA_RO,
  ERR_ECAT_SERVO_COMPARE_ENABLE,

  ERR_ECAT_RECORD_TYPE = 0x1600,

  ERR_ECAT_MPG_ENABLE = 0x1700,
  ERR_ECAT_MPG_CONFIG,

  ERR_ECAT_ROBOT_TYPE = 0x2000,
  ERR_ECAT_ROBOT_INITIAL,
  ERR_ECAT_ROBOT_UPDATE,
  ERR_ECAT_ROBOT_FAILED,
  ERR_ECAT_ROBOT_RESET,
  ERR_ECAT_ROBOT_PARAMETER,
  ERR_ECAT_ROBOT_IN_MOTION,
  ERR_ECAT_ROBOT_BUFFER_FULL,
  ERR_ECAT_ROBOT_NEED_SERVO_OFF,
  ERR_ECAT_ROBOT_V_CHANGING,

  ERR_ECAT_SECURITY_OPERATING = 0x3000,
  ERR_ECAT_SECURITY_NEED_LOGIN,
  ERR_ECAT_SECURITY_CONNECT,

  ERR_ECAT_SPLC_CONNECT_FAILED = 0x4000,
  ERR_ECAT_SPLC_RTSS_FAILED,
  ERR_ECAT_SPLC_KERENL_FILE,
  ERR_ECAT_SPLC_ONGOING,
  ERR_ECAT_SPLC_SDO_FAILED,
  ERR_ECAT_SPLC_ALREADY_RUN,
  ERR_ECAT_SPLC_MOTION_CONFIG_RUN,
  ERR_ECAT_SPLC_MOT_MODE,
  ERR_ECAT_SPLC_HOMING_ERROR,
  ERR_ECAT_SPLC_MOTION_TYPE_ERROR,
  ERR_ECAT_SPLC_MOTION_ERROR,
  ERR_ECAT_SPLC_MOTION_Jog_ERROR,

  //MP相關錯誤
  ERR_ECAT_SPLC_AXISREF_STRUCT = 0x4200,//檢查陣列大小是否正確
  ERR_ECAT_SPLC_MASTER_INDEX_NOT_FOUND,     //卡號錯誤
  ERR_ECAT_SPLC_AXIS_INDEX_NOT_FOUND,       //站號錯誤
  ERR_ECAT_SPLC_MODULE_TYPE,            //模組型態錯誤
  ERR_ECAT_SPLC_FIFO_FULL,            //輸入端資料填滿Buffer
  ERR_ECAT_SPLC_PARAM_INPUT_ERROR,        //輸入端參數錯誤
  ERR_ECAT_SPLC_AXISNUM_ERROR,          //輸入端軸數錯誤
  ERR_ECAT_SPLC_RECORD_FIFO_FULL,
  ERR_ECAT_SPLC_INVALID_MEMORY_PTR,

  //Security
  ERR_ECAT_SPLC_LICENCE_ERROR = 0x4400,//此平台未經過授權

  //Master
  ERR_ECAT_SPLC_EVENT_FAILED = 0x4600,
  ERR_ECAT_SPLC_SHAREMEMORY_FAILED,
  ERR_ECAT_SPLC_MASTER_NOT_FOUND,
  ERR_ECAT_SPLC_MASTER_CONNECT_FAILED,
  ERR_ECAT_SPLC_MASTER_START_SPLC_FAILED,
  ERR_ECAT_SPLC_MASTER_OPEN_eCLR_FAILED,
  ERR_ECAT_SPLC_MASTER_DISCONNECT_FAILED,
  ERR_ECAT_SPLC_MASTER_CLOSE_FAILED,

  ERR_ECAT_PATH_DLL_ERROR_CODE = 0x8000,  // 2018-02-07 from L221
  ERR_PATH_BOARD_INIIT,
  ERR_PATH_INVALID_BOARD_NUMBER,
  ERR_PATH_INITIALIZED_BOARD_NUMBER,
  ERR_PATH_BASE_ADDRESS_ERROR,
  ERR_PATH_BASE_ADDRESS_CONFLICT,
  ERR_PATH_DUPLICATE_BOARD_SETTING,
  ERR_PATH_DUPLICATE_IRQ_SETTING,
  ERR_PATH_ENCNO_ERROR,
  ERR_PATH_MODULENO_ERROR,
  ERR_PATH_TIMER_VALU_EERROR,
  ERR_PATH_ENABLE_ERROR,
  ERR_PATH_RANGE_ERROR,
  ERR_PATH_MEMALLOC_ERROR,
  ERR_PATH_MOTION_BUSY,
  ERR_PATH_MOTION_NOT_START,
  ERR_PATH_SPEED_ERROR,
  ERR_PATH_ACC_TIME_ERROR,
  ERR_PATH_IO_ALARM_ERROR,
  ERR_PATH_OPEN_FILE_FAIL,
  ERR_PATH_MEM_ALLOCATE_ERROR,
  ERR_PATH_MEM_NOT_FREE,
  ERR_PATH_OUTPUT_FILE_NOT_CLOSE,
  ERR_PATH_MOVE_AXIS_NOT_MATCH,
  ERR_PATH_PITCH_ZERO,
  ERR_PATH_TIME_OUT_ERROR,
  ERR_PATH_PCI_BIOS_NOT_EXIST,
  ERR_PATH_BUFFER_FULL,
  ERR_PATH_PATH_ERROR,					// 移動距離為零
  ERR_PATH_MOVE_MODE_ERROR,				// 移動模式錯誤

  ERR_PATH_AXIS_CORRELATION = 0x801F,		// 非設定相關軸,無法執行運動指令,請設定軸相關

  ERR_PATH_SDSTOP_ON = 0x8021,				// 執行SD Stop時,不能下軸運動指令
  ERR_PATH_VELCHANGE_SUPPER,				// 速度變換時,能變換的距離太短
  ERR_PATH_DIR,							// 方向錯誤

  ERR_PATH_P_CHANGE_MODE = 0x8028,			// 必需為單軸指令,而且在單軸移動的模式,而且下達指令時必需為等速段
  ERR_PATH_BUFFER_LENGTH,					// Buffer Length必需要等於零
  ERR_PATH_2SEGMOVE_DIST,					// 距離需要同向
  ERR_PATH_CENTER_MATCH,					// 經過反向運算圓心要一致
  ERR_PATH_END_MATCH,						// 經過反向運算終點要一致
  ERR_PATH_ANGLE_CALCU,					// 經過計算角度錯誤
  ERR_PATH_RADIUS_CALCU,					// 經過計算半徑錯誤
  ERR_PATH_GEAR_SETTING,					// Gear的分子或分母為0
  ERR_PATH_CAMTABLE,						// Table Setting First Arrary Point Error設定table不能到負值table[-1]沒有這種設定
  ERR_PATH_AXES_NUM,						// 多軸設定值必須要兩軸以上
  ERR_PATH_SPIRAL_POS,					// 最終位置會到達螺旋圓心
  ERR_PATH_SPEED_MODE_SLAVE,				// 在速度連續時使用的Slave軸,無法執行Motion指令
  ERR_PATH_SPEED_MODE_SLAVE_SET,			// 設定軸的虛擬必須在軸的前半部
  ERR_PATH_VELCHANGE_HIGH,				// 設定值速度改變過大或是改變sec過長
  ERR_PATH_BACKLASH_STEP,					// accstep+contstep+decstep需小於100
  ERR_PATH_BACKLASH_STATUS,				// 設定時motion done必需為0且buffer length必需為0
  ERR_PATH_DISTOVER,						// 輸入Dist超過TotalDist

  ERR_PATH_PVT_DATA_ERROR = 0x803C,			// PVT motion 輸入的Data有誤
  ERR_PATH_PVT_MODE_ERROR,				// 不支援PVT模式
  ERR_PATH_PVT_CHANNEL,					// channel 必需小於支援PVT的軸數
  ERR_PATH_TM_DATA_AXIS,					// Table Motion 資料軸數超過最大值
  ERR_PATH_TM_CYCLE_DATA,					// Table Motion 循環次數不等於1時，起始點和末點不同
  ERR_PATH_TM_DATA_SIZE,					// 資料個數超過上限
  ERR_PATH_AMF_NUM,						// 濾波超過2道或小於0道
  ERR_PATH_TM_IN_ACTIVE,					// Table Motion 啟動中
  ERR_PATH_TM_BUFFER_FULL,				// 此次新增資料會超過Buffer大小

  ERR_PATH_ECAM_DATA_NUM,					// ECAM資料個數錯誤
  ERR_PATH_ECAM_LENGTH,					// ECAM導程(L) <= 0
  ERR_PATH_ECAM_INDEX,					// ECAM起始Index錯誤
  ERR_PATH_ECAM_DISENGAGE,				// ECAM脫離時機設置錯誤
  ERR_PATH_ECAM_VELOCITY_PERCENT,			// ECAM速度建表，區域百分比錯誤
  ERR_PATH_ECAM_CONSTRUCT_MODE,			// ECAM速度建表，模式填錯(非 0 or 1 or 2)
  ERR_PATH_ECAM_DISENGAGE_PARA,			// ECAM脫離參數未設置
  ERR_PATH_ECAM_CUTLENGTH,				// ECAM自動飛剪切長設置錯誤(太長或太短)
  ERR_PATH_ECAM_REGION,					// ECAM自動飛剪區域設置錯誤(剩餘的等待區角度 > S-Curve 角度)
  ERR_PATH_ECAM_VELOCITY_SCURVE,			// ECAM速度建表，S-Curve 區域設置錯誤(超過停止區大小)
  ERR_PATH_ECAM_GEARNUM,					// ECAM齒輪數目錯誤(有小數點或是為0)
  ERR_PATH_ECAM_KNIFENUM,					// ECAM刀具數目 < 1
  ERR_PATH_ECAM_MASTER_SOURCE,			// ECAM主軸來源設置錯誤
  ERR_PATH_ECAM_HOLDING_AREA,				// ECAM等待區角度太大
  ERR_PATH_ECAM_PARAMETERS,				// ECAM參數設置錯誤
  ERR_PATH_ECAM_MASK_DISTANCE,			// ECAM距離上次對位，未超過設定的遮沒長度
  ERR_PATH_ECAM_COMPENSATE_POSITION,		// ECAM預設的對位位置超過ECAM週期
  ERR_PATH_ECAM_ENGAGED,					// ECAM 嚙合中，無法改對位參數
  ERR_PATH_ECAM_TABLE_EMPTY,				// ECAM Table 是空的
  ERR_PATH_ECAM_COMPENSATE_RANGE,			// ECAM 補償區域錯誤，處發補償時超出可補償的範圍

  ERR_PATH_TP_CIRCLE_DATA = 0x805A,			// 3點走圓，資料輸入錯誤(三點共線)

  ERR_PATH_AMF_ENABLE = 0x805D,				// AMF已啟動
  ERR_PATH_AMF_TIME,						// 濾波次數超出範圍
  ERR_PATH_SPEED_RATIO,					// Table Motion 預改變的速度百分比太大
  ERR_PATH_MOTION_DONE,					// 已Motion Done，不能在加入資料
  ERR_PATH_TM_SD_STOP,					// Table Motion SD STOP 中
  ERR_PATH_TM_FEEDRATE_OVERWRITE,			// Table Motion FeedRate Overwrite 中
  ERR_PATH_IO_NUMBER,						// 超過最大IO數量
  ERR_PATH_PROFILE_MODE_ENABLE,			// TableMotion 速度規劃模式已啟動
  ERR_PATH_NOT_TM_CYCLE_MODE,				// 不是TableMotion Cycle
  ERR_PATH_NONE_ANALYSIS,					// Profile mode 尚未分析
  ERR_PATH_OVER_TABLE_NUM,				// 超過最Table數目
  ERR_PATH_ACCDEC_LIMIT,					// 加速度限制為0
  ERR_PATH_SOFTLIMIT,						// 軟體極限負的位置大於正的位置
  ERR_PATH_TM_ARCBIT,						// TableMotion ArcBit 錯誤(超過三軸),ProfileMOde(超過二軸)
  ERR_PATH_TM_COLLINEAR,					// TableMotion ArcBit 標記的軸三點共線
  ERR_PATH_TM_ARC_ANOTHER_AXIS_POS,		// TableMotion ArcBit 標記的其他軸座標不一樣
  ERR_PATH_TM_PROFILE_PARAMETERS,			// TableMotion ProfileMode 參數設置錯誤。開啟曲線偵測時，ArcRefSpeed 和 ArcRefRadius 不能為 0
  ERR_PATH_GANTRY_NUM,					// 龍門號碼錯誤
  ERR_PATH_GANTRY_PARAMETER,				// 龍門參數錯誤
  ERR_PATH_REVERSE_TORQUE,				// 補償有反向的Torque
  ERR_PATH_POSERROR_CONTROL_DISABLE,		// 位置誤差控制關閉
  ERR_PATH_IN_CHANGE_VEL,					// 正在變速度中
  ERR_PATH_IN_SUPERIMPOSED,				// 此軸 SuperImposed 啟動中
  ERR_PATH_DEC_DIST_NOT_ENOUGHT,			// 減速距離不夠
  ERR_PATH_ADJUSTMENT_AREA_LESS_ZERO,		// 調整區小於0(同步區太長)或刀長小於切長
  ERR_PATH_RC_FS_NO_OVERRANGE,			// RotCut、FlyingShear 超出範圍
  ERR_PATH_PROFILE_DISABLE,				// 凸輪曲線尚未建立
  ERR_PATH_IN_TWO_STAGE_VEL,				// 正再執行2段速運動
  ERR_PATH_NOT_PTP_MOTION,				// 非單軸運動
  ERR_PATH_ROTCUT_SYNC_POS,				// 旋切同步區位置錯誤
  ERR_PATH_NOT_IN_ECAM_MODE,				// 非ECAM模式
  ERR_PATH_SWITCH_PERCENT,				// Cam Switch 百分比設置錯誤
  ERR_PATH_AXIS_DIRECTION,				// 軸方向設置錯誤
  ERR_PATH_ECAM_CURVE_TYPE,				// ECAM 曲線 Type 錯誤(起始、結束曲線為直線 or 有兩直線相接)
  ERR_PATH_ECAM_CAMIN_PARAMETERS,			// ECAM CAMIN 參數設置錯誤(ex:MasterScaling、SlaveScaling、AxisDir......)
  ERR_PATH_ECAM_PROFILE_PARAMETERS,		// ECAM Profile 參數設置錯誤(主軸第一點位置不為0,Master(Slave)Absolute != 0 or 1)
  ERR_PATH_ECAM_TABLE_BEING_USED,			// 此 ECAM Table 正在被使用
  ERR_PATH_ECAM_TABLE_ORIGINAL_RANGE,		// 超過原本 Table 點數
  ERR_PATH_ECAM_FS_PARAMETERS,			// 旋切參數錯誤。主軸開始位置大於主軸同步位置
  // 從軸等待位置大於從軸同步位置
  // 從軸同步位置大於同步結束位置
  ERR_PATH_GEAR_PARAMETERS,				// GearIn 參數錯誤。ex : Ratio 分母為0、加減速為0
  ERR_PATH_ECAM_DATASIZE,					// ECAM 資料點數超過剩餘可用數量
  ERR_PATH_MB_FIFO_FULL,					// Motion Buffer FIFO 滿了
  ERR_PATH_MB_ITP_START,					// Motion Buffer 運動已啟動
  ERR_PATH_FIFO_0_START,					// Motion Buffer FIFO 0 已啟動
  ERR_PATH_GEAR_AXISNO,					// Motion Buffer BufGear 軸號和坐標系的軸號衝突
  ERR_PATH_GEAR_SYNCHRONIZE_NUM,			// Motion Buffer BufGear 同步運動已達上限
  ERR_PATH_MB_IO_ADVANCE,					// Motion Buffer BufGear 同步運動已達上限
  ERR_PATH_MB_NONE_INITIAL,				// Motion Buffer 坐標系尚未建立
  ERR_PATH_MB_CLEAR_BUFFER,				// Motion Buffer 狀態在運動中，無法清除資料
  ERR_PATH_MB_ARC_PARAMETER,				// Motion Buffer Arc 運動參數錯誤，ex:半徑太短,起點和終點一樣
  ERR_PATH_MB_SETCOMMAND,					// Motion Buffer 狀態下無法使用 set command
  ERR_PATH_MB_GEAR_CONTROL,				// Motion Buffer BufGear 後面不可接緩存區指令
  ERR_PATH_PVT_TABLE_FULL,				// PVT Table 已全被使用
  ERR_PATH_PVT_DATA_NONE,					// PVT Table 尚未建立
  //	2017-11-27 New_MultiArc
  ERR_PATH_MULTIARC_INDEX,				// 指定Arc軸位置錯誤
  ERR_PATH_MULTIARC_MODE,					// MultiArc Arc模式錯誤
  ERR_PATH_MOTION_MODE,					// 運動模式錯誤，ex:不是飛剪、旋切、ECAM、Gear_In 狀態
  //	2017-12-18 PVT Gorup
  ERR_PATH_GROUP_ERROR,					// 此軸有群組或此群組已被設立

  ERR_RTX_RTSS_LOAD = 0xD000,
  ERR_RTX_CONNECT_LINK_FAILED,
  ERR_RTX_EVENT_FAILED,
  ERR_RTX_CONNECT_FAILED,
  ERR_RTX_CONFIG_EDITED,
  ERR_RTX_SECURITY_FAILED,
  ERR_RTX_COMMANDING,
  ERR_RTX_RTSS_SYSTEM_NOT_SUPPORT,
  ERR_RTX_NOT_SUPPORT,
  ERR_RTX_THREAD_CREATE_FAILED,
  ERR_RTX_RTSS_START_FAILED,
  ERR_RTX_STACK_START_FAILED,  // 2018-02-07 from PAC
  ERR_RTX_STACK_INITIAL_FAILED,  // 2018-02-07 from PAC
  ERR_RTX_SHM_MEMORY_FAILED,  // 2018-02-07 from PAC
  ERR_RTX_SPLC_LOAD_FAILED,  // 2018-02-07 from PAC

  ERR_RTX_WIN32_SYSTEM_NOT_SUPPORT = 0xD100,
  ERR_RTX_CALLBACK_CLOSE,
  ERR_RTX_CALLBACK_FUNCTION,
  ERR_RTX_CALLBACK_THREAD,

  ERR_RTX_ERRORLOG_NOT_ENABLE = 0xD200,
  ERR_RTX_ERRORLOG_COUNT_ERROR,

  ERR_CARD_NO_FOUND = 0xE000,
  ERR_CARD_NO_RESPONSE,
  ERR_CARD_CONNECT_FAILED,
  ERR_CARD_MEMORY_NOT_ENOUGH,
  ERR_CARD_LOAD_AUTOCONFIG_FILE,
  ERR_CARD_SECURITY_FAILED,
  ERR_CARD_UPGRADE_CREATE_THREAD_FAILED,
  ERR_CARD_UPGRADE_NO_RESPONSE,
  ERR_CARD_UPGRADE_NO_RESOURSE,
  ERR_CARD_UPGRADE_LOAD_RESOURSE,
  ERR_CARD_UPGRADE_TIMEOUT,
  ERR_CARD_UPGRADE_FAILED,
  ERR_CARD_NOT_SUPPORT,  // 2018-02-07 from L221
  ERR_CARD_SHM_CREATE_FAIL,  // 2018-02-07 from L221
  ERR_CARD_OS_TYPE,  // 2018-02-07 from L221
  ERR_DSP_IO_CTRL,  // 2018-02-07 from L221
  ERR_DSP_WRITE_DATA,  // 2018-02-07 from L221
  ERR_DSP_DOWNLOAD_CODE,  // 2018-02-07 from L221
  ERR_DSP_BOOT_MODE,  // 2018-02-07 from L221
  ERR_DSP_NOT_RUNNING,  // 2018-02-07 from L221
  ERR_DSP_NOT_FOUND,  // 2018-02-07 from L221
  ERR_AMP_NOT_RUNNING,  // 2018-02-07 from L221
  ERR_AMP_LOAD_DRIVER,  // 2018-02-07 from L221
  ERR_AMP_CREATE_FILE,  // 2018-02-07 from L221
  ERR_AMP_WRONG_DRIVER,  // 2018-02-07 from L221
  ERR_AMP_MEMORY_MAPPING,  // 2018-02-07 from L221
  ERR_AMP_CANT_STOP,  // 2018-02-07 from L221
  ERR_AMP_DSP_Device_Not_Match,  // 2018-02-07 from L221
  ERR_FPGA_NOT_FOUND,  // 2018-02-07 from L221

  ERR_ECAT_DLL_IS_USED = 0xF000,
  ERR_ECAT_NO_DLL_FOUND,
  ERR_ECAT_NO_RTSS_DLL_FOUND,
  ERR_ECAT_NO_CARD_DLL_FOUND,
  ERR_ECAT_NO_ESI_DLL_FOUND,
  ERR_ECAT_SAME_CARD_NUMBER,
  ERR_ECAT_CARDNO_ERROR,
  ERR_ECAT_GET_DLL_PATH,
  ERR_ECAT_GET_DLL_VERSION,
  ERR_ECAT_NOT_SUPPORT,

  ERR_ECAT_LOADLIB_EMPTY = 0xFFFF
} E_ECAT_ERROR_CODE;


#endif